// Hungarian (magyar) translations. Keys are the exact English strings used by the game; `{0}`-style
// placeholders are filled from the original text (see i18n.js). Accented letters render fine in the canvas font.

// ---- interface text ---------------------------------------------------------------------------
const UI = {
  // shop pages / generic
  "Seeds": "Magok", "Upgrades": "Fejlesztések", "Farm": "Farm", "Gifts": "Ajándékok",
  "{0} reached level {1}!": "{0}: új szint — {1}!",
  "Continue": "Folytatás", "New Game": "Új játék", "Settings": "Beállítások",
  "Music: Off": "Zene: ki", "Music: On": "Zene: be",
  "(silo bonus!)": "(siló bónusz!)", "Harvested {0}!{1}": "Learattad: {0}!{1}",
  "Dismount first (press H).": "Előbb szállj le (H gomb).",
  "Too tired to dig!": "Túl fáradt vagy az ásáshoz!", "You dug up: {0}!": "Kiástad: {0}!",
  "The beds are already tilled.": "Az ágyások már fel vannak szántva.",
  "The soil here isn't yours to till.": "Ezt a földet nem szántogathatod.",
  "Too tired! Sleep at your farmhouse (E at the door).": "Túl fáradt vagy! Aludj a farmházban (E az ajtónál).",
  "Watering can refilled.": "Az öntözőkanna megtelt.",
  "Can is empty — refill it at water.": "A kanna üres — töltsd fel víznél.",
  "Too tired! Sleep at your farmhouse.": "Túl fáradt vagy! Aludj a farmházban.",
  "A sprinkler is in the way.": "Egy locsoló van az úton.",
  "{0} doesn't grow in {1}. ({2})": "{0} nem terem itt: {1}. ({2})",
  "No {0} seeds — Q switches seeds; buy more at the shop.": "Nincs {0} magod — Q: magváltás; vegyél a boltban.",
  "Too hard! Your pickaxe needs an upgrade ({0}).": "Túl kemény! Fejleszd a csákányt ({0}).",
  "Too tired to mine!": "Túl fáradt vagy a bányászathoz!", "Mined {0}!": "Kibányásztad: {0}!", "Broke a rock.": "Széttörtél egy követ.",
  "Select the sword (5) and press Space to fight monsters; the pickaxe (4) breaks ore. Eat food to heal.":
    "Válaszd a kardot (5), és Szóközzel harcolj a szörnyek ellen; a csákány (4) tör ércet. Egyél, hogy gyógyulj.",
  "{0} — find the ladder!": "{0} — keresd meg a létrát!", "Forest": "Erdő",
  "Defeated {0}! Got {1}": "Legyőzted: {0}! Kaptál: {1}", "Defeated {0}!": "Legyőzted: {0}!", "Ouch! -{0} HP": "Au! -{0} HP",
  "You were knocked out in the mine! Lost ${0}.": "Kiütöttek a bányában! Veszteség: ${0}.",
  "Face the water to fish.": "Fordulj a víz felé a horgászathoz.", "Nothing lives here.": "Itt semmi sem él.",
  "Too tired to fish!": "Túl fáradt vagy a horgászathoz!", "Cast! Wait for the bite...": "Bedobtad! Várd meg a kapást...",
  "When the '!' appears press Space, then press Space again while the cursor is in the green zone.":
    "Amikor megjelenik a '!', nyomj Szóközt, majd újra Szóközt, amikor a kurzor a zöld sávban van.",
  "Reeled in.": "Behúztad.", "Caught a {0}! (${1})": "Fogás: {0}! (${1})", "Treasure! +$60": "Kincs! +$60",
  "It got away...": "Elúszott...", "Too slow — it got away.": "Túl lassú voltál — elúszott.",
  "You pet {0}! (bond {1}/5)": "Megsimogattad: {0}! (kötődés {1}/5)", "{0} wags happily.": "{0} boldogan örül.",
  "{0} dug up a Copper Ore!": "{0} kiásott egy rézércet!", "{0} found a {1}!": "{0} talált valamit: {1}!",
  "{0} dug up 3 {1} seeds!": "{0} kiásott 3 db {1} magot!",
  "You don't have a horse. (Shop → Farm page; needs a barn)": "Nincs lovad. (Bolt → Farm oldal; istálló kell hozzá)",
  "Dismounted.": "Leszálltál.", "No riding indoors.": "Bent nem lehet lovagolni.", "Mounted! Press H to get down.": "Felültél! H: leszállás.",
  "Place sprinklers on your farm.": "A locsolókat a farmon helyezheted el.", "Picked up the sprinkler.": "Felvetted a locsolót.",
  "No sprinklers — buy them at the shop (Farm page).": "Nincs locsolód — vegyél a boltban (Farm oldal).",
  "Can't place it there.": "Oda nem teheted.",
  "Sprinkler placed. It waters nearby tilled soil each night.": "Locsoló lerakva. Minden éjjel megöntözi a közeli szántott földet.",
  "You don't have any {0}.": "Nincs nálad {0}.",
  // tutorial (touch, then keyboard)
  "Drag the left joystick to walk. The white square shows the tile you are facing.": "Húzd a bal joystickot a sétához. A fehér négyzet jelöli a mezőt, amerre nézel.",
  "Tap 1 to take the hoe, face some grass and tap A to till the soil.": "Koppints az 1-esre a kapáért, nézz egy füves mezőre, és koppints az A-ra a szántáshoz.",
  "Tap 6 for seeds (Q switches the seed type), then use them on the tilled soil.": "Koppints a 6-osra a magokért (SEED: magváltás), majd használd őket a szántott földön.",
  "Tap 2 for the watering can and water your seeds. Refill it at any pond.": "Koppints a 2-esre az öntözőkannáért, és öntözd meg a magokat. Bármelyik tónál újratöltheted.",
  "Walk to your farmhouse door and tap E, then choose Sleep. Watered crops grow overnight!": "Menj a farmház ajtajához, koppints az E-re, és válaszd az Alvást. Az öntözött növények éjjel nőnek!",
  "Tap A on ripe crops to harvest them, then sell them at the shipping bin next to your house (E).": "Koppints az A-ra az érett növényeknél az aratáshoz, majd add el őket a ház melletti ládában (E).",
  "Explore east to reach the Town. Tap MAP any time for the world map and fast travel.": "Kelet felé találod a várost. A MAP gombbal bármikor megnyithatod a világtérképet és gyorsutazhatsz.",
  "Walk with WASD or the arrow keys. The white square shows the tile you are facing.": "Sétálj WASD-vel vagy a nyilakkal. A fehér négyzet jelöli a mezőt, amerre nézel.",
  "Press 1 to take the hoe, face some grass and press Space to till the soil.": "Nyomd meg az 1-et a kapáért, nézz egy füves mezőre, és Szóközzel szántsd fel.",
  "Press 6 for seeds (Q switches the seed type), then use them on the tilled soil.": "Nyomd meg a 6-ot a magokért (Q: magváltás), majd használd őket a szántott földön.",
  "Press 2 for the watering can and water your seeds. Refill it at any pond.": "Nyomd meg a 2-t az öntözőkannáért, és öntözd meg a magokat. Bármelyik tónál újratöltheted.",
  "Walk to your farmhouse door and press E, then choose Sleep. Watered crops grow overnight!": "Menj a farmház ajtajához, nyomd meg az E-t, és válaszd az Alvást. Az öntözött növények éjjel nőnek!",
  "Press Space on ripe crops to harvest them, then sell them at the shipping bin next to your house (E).": "Szóközzel arasd le az érett növényeket, majd add el őket a ház melletti ládában (E).",
  "Explore east to reach the Town. Press N any time for the world map and fast travel.": "Kelet felé találod a várost. N: világtérkép és gyorsutazás bármikor.",
  "Tutorial complete! Hints can be switched back on in the pause menu (Esc).": "Az oktatás kész! A tippeket a szünet menüben (Esc) vagy a beállításokban kapcsolhatod vissza.",
  "The boat ride to the island costs $50.": "A hajóút a szigetre $50.",
  "You row out to the island ($50). Dig for treasure with the hoe!": "Elevezel a szigetre ($50). Áss kincset a kapával!",
  "You haven't discovered that place yet.": "Ezt a helyet még nem fedezted fel.", "You're already here.": "Már itt vagy.",
  "Travelled to {0} (30 minutes pass).": "Utazás ide: {0} (30 perc telik el).",
  // quests
  "Bring {0} {1}": "Hozz: {0}× {1}", "Defeat {0} {1}s in the mine": "Győzz le {0} db {1} szörnyet a bányában",
  "Mine {0} {1}": "Bányássz: {0}× {1}", "Catch {0} fish": "Fogj {0} halat",
  "Quest complete: {0}! +${1} ({2} is grateful)": "Küldetés kész: {0}! +${1} ({2} hálás)", "Quest: {0} ({1}/{2})": "Küldetés: {0} ({1}/{2})",
  "You need {0} {1}.": "Kell hozzá: {0}× {1}.", "{0} complete! You win ${1}!": "{0} kész! Nyeremény: ${1}!",
  // festivals / dance
  "Get ready!": "Készülj!", "Perfect!": "Tökéletes!", "Oops!": "Hoppá!", "Too slow!": "Túl lassú!",
  "Score {0}/8 — you earn ${1}! {2} enjoyed the dance.": "Pontszám: {0}/8 — keresetted: ${1}! {2} élvezte a táncot.",
  "Rosa: Bring me three different crops for the fair!": "Rosa: Hozz nekem három különböző termést a vásárra!",
  "Rosa: Wonderful display! First prize!": "Rosa: Csodálatos kiállítás! Első díj!",
  "{0}: Bring me a cooked dish for the {1}!": "{0}: Hozz nekem egy főtt ételt a rendezvényre: {1}!", "{0}: Mmm, {1}! Delicious!": "{0}: Mmm, {1}! Isteni!",
  "any fish": "bármilyen hal", "Missing ingredients.": "Hiányzó hozzávalók.", "Cooked {0}!": "Elkészült: {0}!",
  "You're not hungry.": "Nem vagy éhes.", "Ate {0}: +{1} energy & health": "Megetted: {0} — +{1} energia és élet",
  "Talk once a day and give gifts (option 2) to raise friendship. Check what people like in the inventory's Friends tab.":
    "Naponta egyszer beszélgess, és adj ajándékot (2. opció) a barátság növeléséhez. Mit szeretnek az emberek? Nézd meg a tárgylista Barátok fülén.",
  "Accept up to 3 quests. Press J to see your journal; delivery quests are handed in here.": "Legfeljebb 3 küldetést vállalhatsz. J: napló; a szállítós küldetéseket itt add le.",
  "{0}: under construction (ready tomorrow).": "{0}: építés alatt (holnap kész).",
  "Empty plot — buy a {0} at the shop (Farm page).": "Üres telek — a boltban (Farm oldal) megveheted: {0}.",
  "Coop: {0}/{1} chickens.": "Tyúkól: {0}/{1} tyúk.", "Barn: {0}/{1} cows.": "Istálló: {0}/{1} tehén.",
  "Silo: 25% chance of a bonus crop at harvest.": "Siló: 25% eséllyel extra termés aratáskor.",
  "Elevator checkpoint: you'll start on floor {0} next time.": "Lift-ellenőrzőpont: legközelebb a(z) {0}. szintről indulsz.",
  "Oliver is at the festival!": "Oliver a fesztiválon van!", "The shop is closed. (Open 9:00–20:00)": "A bolt zárva. (Nyitva: 9:00–20:00)",
  "Press Tab to flip pages: seeds, upgrades, farm buildings and gifts.": "Tab: lapozás — magok, fejlesztések, épületek, ajándékok.",
  "You saved ${0} and bought the new barn! You win (keep playing!)": "Megspóroltál ${0}-t, és megvetted az új pajtát! Nyertél! (Játssz tovább!)",
  "{0} Lv{1} -> Lv{2}": "{0} Sz{1} -> Sz{2}", "{0} (under construction)": "{0} (építés alatt)", "Build {0}": "Építs: {0}",
  "{0} will be ready tomorrow!": "{0} holnap elkészül!", "5x {0} seeds [{1}]": "5× {0} mag [{1}]",
  "Hoe": "Kapa", "Watering can": "Öntözőkanna", "Pickaxe": "Csákány", "Sword": "Kard",
  "Chicken (build a coop first)": "Tyúk (előbb építs tyúkólat)", "Chicken ({0}/{1})": "Tyúk ({0}/{1})", "Coop full": "Tyúkól tele",
  "Cow (build a barn first)": "Tehén (előbb építs istállót)", "Cow ({0}/{1}) — gives milk daily": "Tehén ({0}/{1}) — naponta ad tejet", "Barn full": "Istálló tele",
  "{0} ({1} tiles; P to place)": "{0} ({1} mező; P: lerakás)",
  "Horse (owned — H to ride)": "Ló (megvan — H: lovaglás)", "Horse (build a barn first)": "Ló (előbb építs istállót)",
  "Horse (ride with H, 1.8x speed)": "Ló (H: lovaglás, 1,8× sebesség)", "You got a horse! Press H to ride.": "Lovat kaptál! H: lovaglás.",
  "Bouquet (give to someone at 8+ hearts to start dating)": "Csokor (8+ szívnél add át valakinek, hogy randizzatok)",
  "Wedding Pendant (give to your partner at 10 hearts)": "Esküvői medál (10 szívnél add a párodnak)",
  "Energy Tonic (+60 energy)": "Energiaital (+60 energia)", "{0} is your pet": "{0} a háziállatod",
  "Adopt a {0} ({1})": "Fogadj örökbe: {0} ({1})", "{0} joins your farm!": "{0} csatlakozott a farmodhoz!",
  "Mystery seeds (5, in season)": "Rejtélyes magok (5 db, szezonális)", "Got 5 {0} seeds!": "Kaptál 5 {0} magot!",
  "Recipe scroll (random recipe)": "Receptlap (véletlen recept)", "Learned {0}!": "Megtanultad: {0}!", "Recipe scroll (sold out)": "Receptlap (elfogyott)",
  "Needs {0}": "Kell hozzá: {0}", "Not enough money!": "Nincs elég pénzed!",
  "Sold everything for ${0}": "Mindent eladtál ${0}-ért", "Sold for ${0}": "Eladva ${0}-ért", "Zed pays ${0}": "Zed fizet: ${0}",
  "{0} perk chosen: {1}!": "{0} képesség: {1}!", "You can only carry 3 quests. Finish one first.": "Csak 3 küldetést vállalhatsz. Előbb fejezz be egyet.",
  "Quest accepted!": "Küldetés elfogadva!", "Game saved.": "Játék mentve.",
  // villager interactions
  "{0}: No festival entries today.": "{0}: Ma nincs fesztiválos feladat.", "{0}: You already gave me something today!": "{0}: Ma már adtál valamit!",
  "{0}: Oh, a {1}. Thanks!": "{0}: Ó, {1}. Köszi!", "{0}: A {1}?! I LOVE it! Thank you!!": "{0}: {1}?! IMÁDOM! Köszönöm!!",
  "{0}: A {1}! That's really nice of you.": "{0}: {1}! Ez nagyon kedves tőled.", "{0}: Ugh... a {1}? No thanks.": "{0}: Úgh... {1}? Nem, köszi.",
  "{0}: That's sweet, but you're already committed!": "{0}: Aranyos, de te már foglalt vagy!",
  "{0}: You're already seeing someone else...": "{0}: Te már mással randizol...",
  "{0}: We're already dating, silly! Maybe a pendant next?": "{0}: Hisz már együtt vagyunk, buta! Talán egy medál legközelebb?",
  "{0}: That's lovely... but I don't know you well enough yet. (needs 8 hearts)": "{0}: Ez szép... de még nem ismerlek elég jól. (8 szív kell)",
  "{0}: A bouquet?! I'd love to be closer to you. We're dating now!": "{0}: Egy csokor?! Szívesen közelebb kerülnék hozzád. Mostantól együtt járunk!",
  "{0}: Oh... we're not at that stage. (give a bouquet first)": "{0}: Ó... még nem tartunk itt. (előbb csokrot adj)",
  "{0}: I'm honored, but not quite yet. (needs 10 hearts)": "{0}: Megtisztelsz, de még nem. (10 szív kell)",
  "{0}: Yes!! Let's marry in 3 days — day {1}!": "{0}: Igen!! Házasodjunk össze 3 nap múlva — a(z) {1}. napon!",
  "{0} gives you ${1} ({2} hearts)!": "{0} ${1}-t ad neked ({2} szív)!", "{0} taught you a recipe: {1}!": "{0} megtanított egy receptre: {1}!",
  "{0} watered {1} crops.": "{0} megöntözött {1} növényt.", "Your {0} is finished!": "Elkészült: {0}!",
  "You married {0}! They now live on the farm.": "Összeházasodtál vele: {0}! Mostantól a farmon élnek.",
  "Rain waters your tilled soil for free today.": "Az eső ma ingyen megöntözi a szántott földet.",
  "Press N for the world map. You can fast travel to places you have visited.": "N: világtérkép. A már meglátogatott helyekre gyorsutazhatsz.",
  "Today: {0}! {1}.": "Ma: {0}! {1}.", "Zed the merchant is in Town today.": "Zed, a kereskedő ma a városban van.",
  "The Town has a shop (seeds, upgrades, farm buildings), a quest board and villagers to befriend.": "A városban van bolt (magok, fejlesztések, épületek), küldetéstábla és falusiak, akikkel barátkozhatsz.",
  "Low energy! Eat food (open the inventory with I, then press a number) or sleep at home.": "Kevés az energia! Egyél (I: tárgylista, majd egy szám) vagy aludj otthon.",
  "Wild forage respawns every morning. Walk over it to pick it up, and sell or gift it.": "A vadon termő növények minden reggel újra nőnek. Sétálj rájuk a felszedéshez; eladhatod vagy odaadhatod.",
  "Found {0}!{1}": "Találtál: {0}!{1}", "You passed out... and woke up at home.": "Elájultál... és otthon ébredtél.",
  "Day {0}": "{0}. nap", "snowing": "havazik", "raining": "esik", "{0} egg(s)": "{0} tojás", "{0} milk": "{0} tej", "collected.": "begyűjtve.",
  "{0} begins!": "{0} kezdődik!", "{0} crop(s) withered.": "{0} növény elszáradt.",
  // HUD / prompts
  "J: {0} quest{1}": "J: {0} küldetés", "HP": "HP",
  "E: pet {0}": "E: simogatás: {0}", "E: trade with Zed": "E: kereskedés Zeddel", "E: talk to {0}": "E: beszélgetés: {0}",
  "Space: harvest": "Szóköz: aratás", "E: sleep / cook": "E: alvás / főzés", "E: community centre": "E: közösségi ház",
  "E: enter greenhouse": "E: üvegház", "E: sell goods": "E: eladás", "E: shop": "E: bolt", "E: enter mine": "E: bánya",
  "E: go down": "E: lefelé", "E: leave mine": "E: kilépés", "Space: fish": "Szóköz: horgászat", "Space: mine": "Szóköz: bányászat",
  "Watering Can": "Öntözőkanna", "Fishing Rod": "Horgászbot", "{0} on the line! Space in the green": "{0} a horgon! Szóköz a zöldben",
  "Tutorial {0}/{1}: {2}": "Oktatás {0}/{1}: {2}", "TIP: {0}": "TIPP: {0}",
  // menus
  "SHOP: {0} (page {1}/{2})  ${3}  Tab: next  E: close": "BOLT: {0} ({1}/{2}. oldal)  ${3}  Tab: tovább  E: bezár",
  "Now: {0}. Out-of-season crops wither when the season changes. Ore and stone come from the mine.": "Most: {0}. Szezonon kívül a növények elszáradnak. Érc és kő a bányából.",
  "SELL  (number sells a stack, A sells all, E to close)": "ELADÁS  (szám: egy köteg, A: mind, E: bezár)",
  "Nothing to sell — harvest, forage, fish or mine!": "Nincs mit eladni — arass, gyűjts, horgássz vagy bányássz!",
  "ZED THE MERCHANT  ${0}  ({1} — Tab to switch, E to close)": "ZED, A KERESKEDŐ  ${0}  ({1} — Tab: váltás, E: bezár)",
  "Zed pays 1.5x for everything:": "Zed mindenért másfélszeres árat fizet:",
  "{0} level {1}: choose a perk": "{0} {1}. szint: válassz képességet", "This choice is permanent.": "Ez a döntés végleges.",
  "TOWN BOARD  (1-4 accept, A/B/C turn in, E close)": "VÁROSI TÁBLA  (1-4: elfogad, A/B/C: leadás, E: bezár)",
  "{0}. {1}  — ${2}  (due day {3}, for {4})": "{0}. {1}  — ${2}  ({3}. napig, {4})",
  "The board is empty. Check back tomorrow.": "A tábla üres. Nézz vissza holnap.", "Your quests ({0}/3):": "Küldetéseid ({0}/3):",
  "{0}. {1} ({2}/{3}) ${4}  due day {5}": "{0}. {1} ({2}/{3}) ${4}  {5}. napig",
  "Deliver quests: bring the items here and press A/B/C. Others complete automatically.": "Szállítós küldetés: hozd ide a tárgyat, majd A/B/C. A többi automatikus.",
  "QUEST JOURNAL  (J / E to close)": "KÜLDETÉSNAPLÓ  (J / E: bezár)",
  "No active quests. Visit the board in Town (next to the plaza).": "Nincs aktív küldetés. Nézd meg a városi táblát (a tér mellett).",
  "— turn in at the board": "— add le a táblánál", "Reward ${0} — for {1} — due day {2}{3}": "Jutalom: ${0} — {1} — {2}. napig{3}",
  "FARMHOUSE": "FARMHÁZ", "1. Sleep (end the day)": "1. Alvás (a nap vége)", "2. Cook": "2. Főzés", "E: cancel": "E: mégse",
  "KITCHEN  (number cooks, E to close)": "KONYHA  (szám: főz, E: bezár)",
  "Eat food from the inventory (I, then a number). Befriend villagers to learn more recipes.": "Egyél a táskából (I, szám). Új receptekért barátkozz a falusiakkal.",
  "PAUSED": "SZÜNET", "1. Resume": "1. Folytatás", "2. Save game": "2. Mentés", "3. Music: {0}": "3. Zene: {0}",
  "4. Tutorial hints: {0}": "4. Oktatási tippek: {0}", "5. Settings": "5. Beállítások", "6. Quit to title": "6. Vissza a címhez",
  "Join the dance": "Csatlakozz a tánchoz", "Festival entry": "Fesztiválos feladat",
  "1. Talk    2. Give gift{0}    E: leave": "1. Beszélgetés    2. Ajándék{0}    E: kilép",
  "Pick a gift (number)  — E: leave": "Válassz ajándékot (szám)  — E: kilép",
  "WORLD MAP  (number = fast travel, 30 min; N / E: close)": "VILÁGTÉRKÉP  (szám = gyorsutazás, 30 perc; N / E: bezár)",
  "YOU": "TE", "+ Greenhouse": "+ Üvegház", "+ Mine (Forest)": "+ Bánya (Erdő)",
  "1. Farm   2. Town   3. Forest   4. Beach   5. Desert   6. Island ($50)": "1. Farm   2. Város   3. Erdő   4. Part   5. Sivatag   6. Sziget ($50)",
  "COMMUNITY CENTRE {0}  E: {1}": "KÖZÖSSÉGI HÁZ {0}  E: {1}", "DONE": "KÉSZ", "{0}. {1}  {2}/{3}  — reward ${4}{5}": "{0}. {1}  {2}/{3}  — jutalom: ${4}{5}",
  "Complete all bundles to restore the centre and win ${0}!": "Teljesítsd az összes csomagot a ház felújításához, és nyerj ${0}-t!",
  "Pick a bundle, then press an item's number to deposit it (any N of the list).": "Válassz csomagot, majd nyomd meg a tárgy számát a beadáshoz (bármelyik elem jó).",
  "({0}/{1} bundles)": "({0}/{1} csomag)", "(restored!)": "(felújítva!)", "back": "vissza", "close": "bezár",
  "{0}: deposit any {1} ({2}/{3})  reward ${4}": "{0}: adj be {1} különbözőt ({2}/{3})  jutalom: ${4}", "(you have {0})": "(nálad: {0})",
  "THE COMMUNITY CENTRE IS RESTORED!": "A KÖZÖSSÉGI HÁZ FELÚJÍTVA!",
  "The whole valley gathers to celebrate what you've built.": "Az egész völgy összegyűlik, hogy megünnepelje, amit felépítettél.",
  "Days played: {0}   Money: ${1}   Fish caught: {2}": "Játszott napok: {0}   Pénz: ${1}   Fogott halak: {2}", "Skills: {0}": "Képességek: {0}",
  "Married: {0}   Pet: {1}   Horse: {2}": "Házastárs: {0}   Háziállat: {1}   Ló: {2}", "You received ${0} as a thank-you.": "${0}-t kaptál köszönetül.",
  "Thanks for playing Tiny Valley! Keep farming as long as you like.": "Köszönjük, hogy játszottál a Tiny Valley-vel! Gazdálkodj, ameddig csak szeretnél.",
  "(press any key)": "(nyomj egy gombot)", "Dance": "Tánc", "{0} — with {1}": "{0} — {1} társaságában",
  "Match the arrow! (WASD / arrows)  {0}/8": "Találd el a nyilat! (WASD / nyilak)  {0}/8", "Perfect": "Tökéletes", "Score {0}": "Pontszám: {0}", "Press any key": "Nyomj egy gombot",
  "[ITEMS]  friends  skills": "[TÁRGYAK]  barátok  képességek", "items  [FRIENDS]  skills": "tárgyak  [BARÁTOK]  képességek", "items  friends  [SKILLS]": "tárgyak  barátok  [KÉPESSÉGEK]",
  "{0}   (Tab: switch, I/E: close)": "{0}   (Tab: váltás, I/E: bezár)",
  "Hoe L{0}  Can L{1} ({2})  Pick L{3}  Sword L{4}": "Kapa Sz{0}  Kanna Sz{1} ({2})  Csákány Sz{3}  Kard Sz{4}",
  "Fish caught {0}  Mine best {1}F": "Fogott hal: {0}  Bánya rekord: {1}. szint",
  "Seeds (Q switches)        Season  Sell": "Magok (Q: váltás)         Évszak  Ár",
  "Bag (number = eat)": "Táska (szám = eszik)", "…and {0} more": "…és még {0}", "Worth ${0}": "Értéke: ${0}", "{0}  Lv {1}{2}": "{0}  Sz {1}{2}",
  "Max HP {0}": "Max HP: {0}", "none yet (levels 5 and 10)": "még nincs (5. és 10. szint)", "Perks: {0}": "Képességek: {0}", "Loves: {0}": "Kedvence: {0}",
  "Married to {0}": "Házastárs: {0}", "Engaged to {0} — wedding on day {1}": "Jegyes: {0} — esküvő a(z) {1}. napon", "Dating {0}": "Randi: {0}",
  "Single (8 hearts + bouquet to date, 10 + pendant to marry)": "Egyedülálló (8 szív + csokor a randihoz, 10 + medál a házassághoz)",
  "Recipes: {0}": "Receptek: {0}", "Chickens {0}/{1}  Cows {2}/{3}  Goal ${4}/{5}  Zed every {6}th day": "Tyúk {0}/{1}  Tehén {2}/{3}  Cél ${4}/{5}  Zed minden {6}. napon",
  "TINY VALLEY": "TINY VALLEY", "a cozy farming adventure": "egy hangulatos farmos kaland",
  "W/S select · Enter start · M toggles music · O settings": "W/S: választ · Enter: indít · M: zene · O: beállítások",
  // settings
  "SETTINGS": "BEÁLLÍTÁSOK", "Language: {0}": "Nyelv: {0}", "Music: {0}": "Zene: {0}", "Sound effects: {0}": "Hangeffektek: {0}",
  "Tutorial hints: {0}": "Oktatási tippek: {0}", "Touch controls: {0}": "Érintőgombok: {0}", "Vibration: {0}": "Rezgés: {0}", "E / O: close": "E / O: bezár",
  "on": "be", "off": "ki", "Small": "Kicsi", "Medium": "Közepes", "Large": "Nagy",
  // maps
  "Town": "Város", "Beach": "Part", "Desert": "Sivatag", "Island": "Sziget", "Mine {0}F": "Bánya {0}. szint",
  "Tap ⟳ to rotate the game for a bigger view • Add to Home Screen to install": "Koppints a ⟳ gombra a nagyobb képért (játék elforgatása) • Add hozzá a kezdőképernyőhöz",
  "Phone screen: {0}": "Telefon képernyő: {0}", "Upright": "Álló", "Rotated right": "Elforgatva jobbra", "Rotated left": "Elforgatva balra",
  "{0} seeds": "{0} mag", "en": "e", "forage": "vadon termő", "BUY": "VÉTEL", "SELL": "ELADÁS", "English": "English", "Magyar": "Magyar", "TAB": "TAB",
  // story intro
  "Gray towers. Gray mornings. Another year of numbers on a screen, and the sky never changed.": "Szürke tornyok. Szürke reggelek. Újabb év számok között egy képernyő előtt, és az égbolt sosem változott.",
  "Then, one rainy evening, a thick envelope arrived. It smelled of woodsmoke and old soil.": "Aztán egy esős estén megérkezett egy vastag boríték. Fafüst és régi föld illata volt.",
  "My dear grandchild,": "Drága unokám,",
  "Tiny Valley's old farm is yours now. The soil is rich, the neighbours are kind — but the community centre, where the whole valley once gathered, has fallen into ruin.": "A Tiny Valley-i régi farm mostantól a tiéd. A föld termékeny, a szomszédok kedvesek — de a közösségi ház, ahol egykor az egész völgy összegyűlt, romokban hever.",
  "Restore it, and the valley will bloom again. I believe in you.": "Állítsd helyre, és a völgy újra virágba borul. Hiszek benned.",
  "— Grandpa Walt": "— Walt nagypapa",
  "You packed one bag, left the grey city behind, and followed the road into the sunrise.": "Egyetlen táskát pakoltál, magad mögött hagytad a szürke várost, és követted az utat a napfelkeltébe.",
  "The fields were wild and the fences crooked — but smoke curled from the chimney. This was home now.": "A mezők vadak voltak, a kerítések görbék — de a kéményből füst kunkorodott. Mostantól ez volt az otthonod.",
  "Spring, Day 1": "Tavasz, 1. nap", "Restore the community centre.": "Állítsd helyre a közösségi házat.", "Welcome to Tiny Valley.": "Üdv Tiny Valley-ben.",
  "Skip ▶": "Kihagyás ▶", "Esc: skip": "Esc: kihagyás",
  // static page labels
  "INV": "TÁSKA", "QUEST": "KÜLD.", "SEED": "MAG", "MENU": "MENÜ", "MAP": "TÉRKÉP", "RIDE": "LÓ", "PLACE": "LOCSOLÓ", "MUSIC": "ZENE", "BACK": "VISSZA",
  // seasons
  "Spring": "Tavasz", "Summer": "Nyár", "Fall": "Ősz", "Winter": "Tél",
};

// ---- names (capitalised; lowercase variants are generated below) -----------------------------------
const NAMES = {
  Coop: "Tyúkól", Barn: "Istálló", Silo: "Siló", Greenhouse: "Üvegház",
  Dog: "Kutya", Cat: "Macska", Slime: "Nyálka", Bat: "Denevér", Skeleton: "Csontváz",
  Milk: "Tej", "Bat Wing": "Denevérszárny", Bone: "Csont", Bouquet: "Csokor", "Wedding Pendant": "Esküvői medál", "Energy Tonic": "Energiaital",
  Pearl: "Gyöngy", "Ancient Coin": "Ókori érme", "Old Relic": "Régi ereklye", Sprinkler: "Locsoló", "Quality Sprinkler": "Minőségi locsoló",
  "Wild Leek": "Vad póréhagyma", Daffodil: "Nárcisz", "Spice Berry": "Fűszerbogyó", "Wild Grape": "Vadszőlő", Mushroom: "Gomba", Blackberry: "Szeder",
  Holly: "Magyal", "Snow Yam": "Hóbatáta", Seashell: "Kagyló", Coral: "Korall", "Sea Urchin": "Tengeri sün", "Cactus Fruit": "Kaktuszgyümölcs",
  "Sand Rose": "Homokrózsa", Coconut: "Kókuszdió", Starfruit: "Csillaggyümölcs",
  Carp: "Ponty", Bluegill: "Naphal", Goldfish: "Aranyhal", Perch: "Sügér", Bass: "Fekete sügér", Pike: "Csuka", Trout: "Pisztráng", Salmon: "Lazac",
  Catfish: "Harcsa", Sardine: "Szardínia", Octopus: "Polip", Tuna: "Tonhal", Pufferfish: "Gömbhal", Lionfish: "Oroszlánhal", Swordfish: "Kardhal", Sandfish: "Homokhal",
  Stone: "Kő", "Copper Ore": "Rézérc", "Iron Ore": "Vasérc", "Gold Ore": "Aranyérc", Amethyst: "Ametiszt", Aquamarine: "Akvamarin", Ruby: "Rubin",
  "Fried Egg": "Tükörtojás", "Turnip Stew": "Fehérrépa-főzelék", "Veggie Soup": "Zöldségleves", "Pumpkin Pie": "Sütőtökös pite", "Fish Stew": "Halászlé",
  "Forest Salad": "Erdei saláta", Pancakes: "Palacsinta", Sushi: "Szusi", "Cactus Jam": "Kaktuszlekvár", Ratatouille: "Ratatouille", "Coconut Pudding": "Kókuszpuding", Cornbread: "Kukoricakenyér",
  Egg: "Tojás", Turnip: "Fehérrépa", Potato: "Burgonya", Carrot: "Répa", Tomato: "Paradicsom", Corn: "Kukorica", Pumpkin: "Sütőtök", Eggplant: "Padlizsán", Cabbage: "Káposzta", Kale: "Kelkáposzta",
  Farming: "Gazdálkodás", Fishing: "Horgászat", Mining: "Bányászat", Foraging: "Gyűjtögetés", Combat: "Harc",
  Baker: "Pék", Shopkeeper: "Boltos", Angler: "Horgász", "Retired farmer": "Nyugdíjas gazda", "Beach fisher": "Tengerparti halász", "Desert nomad": "Sivatagi nomád", Botanist: "Botanikus", Writer: "Író",
  "Crop Bundle": "Termés csomag", "Forager's Bundle": "Gyűjtögető csomag", "Angler's Bundle": "Horgász csomag", "Miner's Bundle": "Bányász csomag",
  "Coast Bundle": "Tengerparti csomag", "Kitchen Bundle": "Konyhai csomag", "Monster Bundle": "Szörny csomag",
  "Egg Hunt": "Tojásvadászat", "Flower Dance": "Virágtánc", "Beach Luau": "Tengerparti lakoma", "Fishing Derby": "Horgászverseny", "Harvest Fair": "Aratóvásár",
  "Farmers' Market": "Gazdapiac", "Ice Fishing": "Jégvarsás", "Winter Feast": "Téli lakoma", "Starlight Dance": "Csillagfény-tánc",
  Tiller: "Szántóvető", Rancher: "Tenyésztő", Agriculturist: "Agronómus", Artisan: "Mester", Fisher: "Halász", Trapper: "Csapdázó", Pirate: "Kalóz",
  Miner: "Bányász", Geologist: "Geológus", Prospector: "Kincskereső", Blacksmith: "Kovács", Gatherer: "Gyűjtő", Tracker: "Nyomkereső", Naturalist: "Természetbúvár",
  Fighter: "Harcos", Defender: "Védő", Brute: "Vadállat", Acrobat: "Akrobata",
};

// ---- longer texts: festival blurbs, perks, skills ---------------------------------------------------
const TEXT = {
  "Collect 10 festival eggs in Town": "Gyűjts 10 fesztiváli tojást a városban", "Talk to Rosa in Town to dance": "Beszélj Rosával a városban, hogy táncolj",
  "Give Marlo a cooked dish on the beach": "Adj Marlónak egy főtt ételt a parton", "Catch 5 fish today": "Fogj ma 5 halat",
  "Show Rosa 3 different crops (talk to her)": "Mutass Rosának 3 különböző termést (beszélj vele)", "Everything you sell is worth 25% more today": "Minden ma eladott dolog 25%-kal többet ér",
  "Catch 3 fish today": "Fogj ma 3 halat", "Give Rosa a cooked dish (talk to her)": "Adj Rosának egy főtt ételt (beszélj vele)",
  "+3% crop sale price per level": "+3% termésár szintenként", "wider catch zone, +3% fish price per level": "szélesebb fogási sáv, +3% halár szintenként",
  "extra ore chance; cheaper swings at Lv4 / Lv8": "több érc esélye; olcsóbb ütések a 4. / 8. szinten",
  "double-find chance, +3% forage price per level": "dupla találat esélye, +3% gyűjtögetett ár szintenként",
  "+5 max HP per level, tougher at Lv3 / Lv6 / Lv9": "+5 max HP szintenként, edzettebb a 3. / 6. / 9. szinten",
  "Crops sell for 10% more": "A termések 10%-kal többet érnek", "Eggs and milk sell for 30% more": "A tojás és a tej 30%-kal többet ér",
  "Watered crops have a 25% chance to grow an extra day": "Az öntözött növények 25% eséllyel egy nappal többet nőnek", "Cooked dishes sell for 40% more": "A főtt ételek 40%-kal többet érnek",
  "Fish sell for 25% more": "A halak 25%-kal többet érnek", "Fish bite twice as fast": "A halak kétszer olyan gyorsan kapnak", "A much wider catch zone": "Sokkal szélesebb fogási sáv",
  "20% chance of a $60 treasure with each catch": "Minden fogásnál 20% esély $60 értékű kincsre", "+20% chance of extra ore": "+20% esély extra ércre",
  "8% chance a node also yields an amethyst": "8% eséllyel az érctömb ametisztet is ad", "Mining costs 1 less energy": "A bányászat 1-gyel kevesebb energiába kerül",
  "Ore sells for 40% more": "Az érc 40%-kal többet ér", "+20% chance to double a forage find": "+20% esély a gyűjtögetett lelet megduplázására",
  "Forage sells for 25% more": "A gyűjtögetett növények 25%-kal többet érnek", "50% more forage appears each day": "Naponta 50%-kal több vadon termő növény jelenik meg",
  "Raw crops and forage restore 3x energy": "A nyers termések és gyűjtögetett növények 3× annyi energiát adnak", "Sword damage +1": "Kardsebzés +1", "+25 max HP": "+25 max HP",
  "Sword damage +1 more": "Kardsebzés még +1", "Longer invulnerability after a hit": "Hosszabb sebezhetetlenség találat után",
  "Good morning, love! Ready for another day on the farm?": "Jó reggelt, drágám! Készen állsz egy újabb farmos napra?",
  "I watered a few crops for you. Don't work too hard!": "Megöntöztem pár növényt helyetted. Ne dolgozz túl sokat!",
  "I'm so lucky to share this farm with you.": "Olyan szerencsés vagyok, hogy veled oszthatom meg ezt a farmot.",
  "Dinner tonight? I'll cook something nice.": "Vacsora ma este? Főzök valami finomat.", "The valley feels like home because of you.": "A völgy miattad érződik otthonnak.",
};

// ---- villager dialogue ------------------------------------------------------------------------------
const TALK = {
  // Rosa
  "Welcome to the valley! I'm Rosa — I run the bakery.": "Üdv a völgyben! Rosa vagyok — én vezetem a pékséget.",
  "Water your crops every day, newcomer.": "Öntözd a növényeidet minden nap, jövevény.", "Nice weather for farming, isn't it?": "Szép idő ez a gazdálkodáshoz, nem igaz?",
  "Your farm is coming along nicely!": "A farmod szépen alakul!", "I'd love to bake with your pumpkins sometime.": "Szívesen sütnék a sütőtökeidből egyszer.",
  "Cook at your farmhouse — E on the door.": "Főzz a farmházadban — E az ajtónál.", "You're the best thing to happen to this town.": "Te vagy a legjobb, ami ezzel a várossal történhetett.",
  "Come by the bakery any time — there's always a seat for you.": "Nézz be a pékségbe bármikor — mindig van egy hely neked.", "I saved you a loaf. Don't tell Oliver.": "Félretettem neked egy cipót. Ne áruld el Olivernek.",
  "Spring means daffodils. My favorite!": "A tavasz a nárciszokat jelenti. A kedvencem!", "Summer tomatoes make the sweetest sauce.": "A nyári paradicsomból lesz a legédesebb szósz.",
  "Autumn pumpkins... perfection.": "Az őszi sütőtök... tökéletes.", "Cabbage and kale survive winter.": "A káposzta és a kelkáposzta átvészeli a telet.",
  // Oliver
  "Welcome to the shop. Seeds and upgrades inside.": "Üdv a boltban. Bent magok és fejlesztések vannak.", "Out-of-season crops wither when the season changes. Plan ahead.": "A szezonon kívüli növények elszáradnak évszakváltáskor. Tervezz előre.",
  "Upgrades need ore from the mine. Bring copper!": "A fejlesztésekhez érc kell a bányából. Hozz rezet!", "Upgrade your hoe and can to work several tiles at once.": "Fejleszd a kapát és a kannát, hogy egyszerre több mezőn dolgozz.",
  "Chickens lay eggs every night. Cheap income!": "A tyúkok minden éjjel tojnak. Olcsó bevétel!", "I've been saving the good seeds for you.": "A jó magokat neked tartogattam.",
  "You keep this shop in business. Thank you, friend.": "Neked köszönhetően működik ez a bolt. Köszönöm, barátom.", "If I could farm like you, I'd close up shop tomorrow.": "Ha úgy gazdálkodhatnék, mint te, holnap bezárnám a boltot.",
  "Take care of yourself out there.": "Vigyázz magadra odakint.", "Spring seeds sell fastest.": "A tavaszi magok fogynak a leggyorsabban.", "Summer is tomato and corn season.": "A nyár a paradicsom és a kukorica ideje.",
  "Fall's pumpkins pay the best.": "Az őszi sütőtök fizet a legjobban.", "Winter's quiet. I do my accounting.": "A tél csendes. Ilyenkor végzem a könyvelést.",
  // Mina
  "Shh! You'll scare the fish.": "Pszt! Elijeszted a halakat.", "Face the water with your rod and press Space to cast.": "Fordulj a víz felé a horgászbottal, és Szóközzel dobd be.",
  "The lake has bigger fish than your farm pond.": "A tóban nagyobb halak vannak, mint a farmod tavában.", "When you see the '!', press Space right away.": "Amint meglátod a '!'-t, azonnal nyomj Szóközt.",
  "Time the bar — press Space while the cursor is in the green.": "Időzítsd a sávot — nyomj Szóközt, amikor a kurzor a zöldben van.", "Trout are tricky, but they sell well.": "A pisztráng nehéz, de jó áron megy.",
  "You've got the patience of a true angler.": "Igazi horgász türelmed van.", "I caught a catfish this big once. Honest!": "Egyszer egy ekkora harcsát fogtam. Becsszó!",
  "Fishing with you is the best part of my day.": "A veled való horgászat a napom legjobb része.", "Spring bass and pike are biting.": "Tavasszal a sügér és a csuka kap.",
  "Summer catfish hide in the shade.": "Nyáron a harcsák az árnyékban rejtőznek.", "Autumn salmon run upstream.": "Ősszel a lazacok felfelé úsznak.", "Winter fish are slow, but so am I.": "A téli halak lassúak, de én is.",
  // Ben
  "Back in my day we hoed by hand. Uphill. Both ways.": "Az én időmben kézzel kapáltunk. Felfelé. Mindkét irányba.", "The forest is full of free food if you look.": "Az erdő tele van ingyen élelemmel, ha figyelsz.",
  "Hm. A new farmer. We'll see.": "Hm. Egy új gazda. Meglátjuk.", "Not bad for a beginner, I'll admit.": "Nem rossz egy kezdőtől, ezt elismerem.", "There's a mine in the forest. Bring a pickaxe.": "Az erdőben van egy bánya. Vigyél csákányt.",
  "Mushrooms in fall, holly in winter. Remember that.": "Ősszel gomba, télen magyal. Jegyezd meg.", "You remind me of myself, forty years ago.": "Önmagamra emlékeztetsz negyven évvel ezelőttről.",
  "This old farm is in good hands with you.": "Ez a régi farm jó kezekben van veled.", "Take my advice: never skip watering.": "Fogadd meg a tanácsom: sose hagyd ki az öntözést.",
  "Leeks and daffodils pop up in spring.": "Tavasszal póréhagyma és nárcisz bújik elő.", "Berries and grapes in summer.": "Nyáron bogyók és szőlő.",
  "Mushrooms and blackberries in fall.": "Ősszel gomba és szeder.", "Holly and snow yams in winter. Dress warm.": "Télen magyal és hóbatáta. Öltözz melegen.",
  // Marlo
  "The ocean's big, friend. Big fish out there.": "Nagy az óceán, barátom. Nagy halak vannak odakint.", "Ocean fish bite differently. Be quick!": "Az óceáni halak másképp kapnak. Légy gyors!",
  "Care for a chat? The tide's patient.": "Beszélgetnél egy kicsit? Az apály türelmes.", "Tuna in summer, octopus in winter.": "Nyáron tonhal, télen polip.",
  "Collect shells and coral along the shore.": "Gyűjts kagylót és korallt a part mentén.", "Pufferfish are tricky — but pay great.": "A gömbhal nehéz — de nagyon jól fizet.",
  "You fish like you were born on the water.": "Úgy horgászol, mintha a vízen születtél volna.", "Stay for sunset. It's the best part.": "Maradj a naplementéig. Az a legszebb rész.",
  "I'd sail anywhere with you.": "Bárhová vitorlázanék veled.", "Spring tides bring sardines.": "A tavaszi dagály szardíniát hoz.", "Summer means tuna and pufferfish.": "A nyár tonhalat és gömbhalat jelent.",
  "Autumn tuna are fat and slow.": "Az őszi tonhal kövér és lassú.", "Winter octopus hide in the rocks.": "A téli polipok a sziklák közt bújnak meg.",
  // Dune
  "Hello, traveler. The sand keeps many secrets.": "Üdv, utazó. A homok sok titkot rejt.", "Mind the sun. Water is life out here.": "Vigyázz a nappal. Itt a víz maga az élet.",
  "Cactus fruit is sweeter than it looks.": "A kaktuszgyümölcs édesebb, mint amilyennek látszik.", "The oasis holds a fish found nowhere else.": "Az oázisban él egy hal, amilyen máshol nincs.",
  "Sand roses sell for a fortune.": "A homokrózsák egy vagyont érnek.", "I walk this desert every day. It never looks the same.": "Minden nap bejárom ezt a sivatagot. Sosem néz ki ugyanúgy.",
  "You're the first stranger I've trusted in years.": "Te vagy az első idegen, akiben évek óta megbízom.", "Come, I'll show you the best dunes.": "Gyere, megmutatom a legszebb dűnéket.",
  "The desert is kinder with good company.": "A sivatag kedvesebb jó társasággal.", "Spring brings a rare cool breeze.": "A tavasz ritka, hűs szellőt hoz.",
  "Summer here is no joke. Stay hydrated.": "Itt a nyár nem tréfa. Igyál sokat.", "Autumn nights are bright with stars.": "Az őszi éjszakák fényesek a csillagoktól.", "Even desert winters bite at night.": "Még a sivatagi tél is csíp éjjel.",
  // Iris
  "Oh! I didn't hear you over the birdsong.": "Ó! Nem hallottalak a madárcsicsergéstől.", "Plants talk if you listen long enough.": "A növények beszélnek, ha elég sokáig hallgatod őket.",
  "The forest soil is rich. Better than your farm, probably.": "Az erdő talaja gazdag. Valószínűleg jobb, mint a farmodé.", "Ever tried kale in winter? Underrated.": "Próbáltál már télen kelkáposztát? Alulértékelt.",
  "A greenhouse lets you grow anything, any time.": "Egy üvegházban bármit termeszthetsz, bármikor.", "I keep a notebook of every flower in the valley.": "Füzetet vezetek a völgy minden virágáról.",
  "You've got a gardener's heart.": "Kertész szíved van.", "Let me show you my secret mushroom patch some day.": "Majd egyszer megmutatom a titkos gombafoltomat.",
  "Everything blooms nicer when you're around.": "Minden szebben virágzik, ha a közelben vagy.", "Spring is the busiest season for botanists.": "A tavasz a legnyüzsgőbb évszak egy botanikusnak.",
  "Summer sun makes everything grow wild.": "A nyári nap mindent vadul növeszt.", "Autumn colors are my favorite palette.": "Az őszi színek a kedvenc palettám.", "Winter sleep is just plants gathering strength.": "A téli álom csak a növények erőgyűjtése.",
  // Quill
  "Shh, I'm in the middle of a sentence.": "Pszt, egy mondat közepén vagyok.", "I write about this valley. Don't worry, you're only a footnote.": "Erről a völgyről írok. Ne aggódj, te csak egy lábjegyzet vagy.",
  "Writer's block is the real monster.": "Az írói válság az igazi szörnyeteg.", "You might make it into chapter two.": "Lehet, hogy bekerülsz a második fejezetbe.",
  "I hear there's an island past the beach. Material!": "Úgy hallom, a parton túl van egy sziget. Alapanyag!", "Treasure hunters make the best characters.": "A kincsvadászok a legjobb szereplők.",
  "I've written you a whole chapter. It's too flattering to show you.": "Egy egész fejezetet írtam rólad. Túl hízelgő ahhoz, hogy megmutassam.", "Every story needs someone like you.": "Minden történetnek kell valaki, mint te.",
  "Come back tomorrow. I'll read you the ending.": "Gyere vissza holnap. Felolvasom a végét.", "Spring is for new beginnings. Cliché, but true.": "A tavasz az új kezdetek ideje. Közhely, de igaz.",
  "Summer afternoons are for notebooks and lemonade.": "A nyári délutánok a jegyzetfüzeté és a limonádéé.", "Autumn is when the words flow best.": "Ősszel folynak legjobban a szavak.", "Winter nights are for finishing manuscripts.": "A téli éjszakák a kéziratok befejezéséé.",
};

const lower = s => s[0].toLowerCase() + s.slice(1);
const extra = {};
for (const [en, hu] of Object.entries(NAMES)) if (!/\s/.test(en)) extra[lower(en)] = lower(hu);

export const HELP_HU = "WASD/nyilak: mozgás · 1-6: eszközök · Szóköz: használat · E: interakció · I: táska · J: küldetések · H: ló · N: térkép · O: beállítások · Esc: szünet<br>Cél: állítsd helyre a közösségi házat";
export const HU = { ...UI, ...NAMES, ...TEXT, ...TALK, ...extra };
